### ISSUE TITLE
Code blocks should be scrollable

### ISSUE THREAD

**Issue by julianlam** [NodeBB/nodebb-theme-vanilla#41]
Through use of media queries:

``` less
pre {
    overflow-x: auto;
}
```

... additionally, on Lavender:

``` less
pre {
    max-height: 450px;
    overflow-y: auto;
}
```

... and on mobile:

``` less
@media (min-width: @screen-sm-min) {
    pre {
        max-height: 150px;
    }
}
```
